### ISSUE TITLE
Choose a specific core or thread to disable

### ISSUE THREAD

**Issue by Rinzheim** [NGnius/PowerTools#12]
**Describe what you'd like to be able to do**
I'd like to be able to choose wich specific core or thread I would like to disable
**Describe alternatives you've considered**
Slider is fast and intuitive, I would like to keep the slider but I feel like adding an advance tab for specific options would be ideal.

**Comment by Rinzheim** [comment]
Can't describe an specific situation, but for example with a slider I can't have 4 cores and one thread enabled

**Comment by logan2611** [comment]
Why would it be useful to have all 4 cores enabled but only 1 thread

**Comment by NGnius** [comment]
Now that the React update is almost complete, similar functionality may be made available with the advanced CPU stuff in the next couple of updates. But it won't allow that specific thing, because I'm still waiting for a situation where that could be useful.

I probably wouldn't say no to a PR with this functionality, I'm just not going to work on it myself.
