### ISSUE TITLE
Save settings for Dolphin emulator 

### ISSUE THREAD

**Issue by Onkeyuk** [NGnius/PowerTools#20]
The Dolphin emulator seems to run much better using power tools and turning off cpu smt to half the threads. 

I have to do this every time I load a game. I’m using steam rom manager that came with Emudeck to launch games from the steam game mode. 
it would be amazing to have a settings profile for emulators like dolphin

**Comment by NGnius** [comment]
The current game detection uses the currently-running Steam game as detected by Steam. How else would you propose that work?

**Comment by Onkeyuk** [comment]
> The current game detection uses the currently-running Steam game as detected by Steam. How else would you propose that work?

I’m not quite sure how it works but other emulators like Yuzu get picked up in steam profiles so I can apply custom settings. 
map maybe it’s a dolphin thing that needs something doing so steam can save settings just for it

**Comment by NGnius** [comment]
When you launch a game for the Dolphin emulator what does PowerTools say you're playing?

**Comment by Samuel-B-D** [comment]
@Onkeyuk You can add dolphin as a non-steam game (or even each specific games by making a non-steam-game with the command `--exec=<iso_path>` to launch that game).
If running like that, the steam game detection will work.

**Comment by Onkeyuk** [comment]
Amazing, thank you!

**Comment by Samuel-B-D** [comment]
> Amazing, thank you!
> […](#)
> On 2 Aug 2022, at 13:24, Samuel Bergeron-Drouin ***@***.***> wrote: ﻿ @Onkeyuk You can add dolphin as a non-steam game (or even each specific games by making a non-steam-game with the command --exec=<iso_path> to launch that game). If running like that, the steam game detection will work. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.

Sorry, I removed my comment because I didn't realize you were alrealy launching through the Gaming Mode with shortcuts made by Emudeck.

Emudeck basically just auto-configure what I had explained to make your library available in gaming mode.
If you've been playing like this, then it should alrealy be ok?

**Comment by NGnius** [comment]
You can currently copy your settings for one game to another by copying files in `~/.config/powertools/` (each file corresponds to a unique Steam game's AppId). The next release is going to break compatibility with existing config files, so it's a great time to start organizing them.

I'm not going to add some way to do that within PowerTools itself, since there's no good (non-janky) way to do it that I can think of. Maybe one of the programs that adds all of those games as separate entries in Steam will add a way to automatically replicate PowerTools configs across those games as well (I can dream lol).
