### ISSUE TITLE
"Best Core"-aware slider

### ISSUE THREAD

**Issue by Samuel-B-D** [NGnius/PowerTools#24]
Looking back at this issue #12, I am not sure the anwser [here](https://github.com/NGnius/PowerTools/issues/12#issuecomment-1136176022) is completely right;
I am not sure if it apply to the Steam Deck's APU specifically, but since Zen 2, AMD's CPUs have a notion of "best core" (and second-best-core), which identify which core of that particular CPU's silicon perform better and usually boost higher than the other cores.
In windows, the scheduler is aware of that and will try to assign game's main thread to this core for better performances.
https://www.anandtech.com/show/15137/amd-clarifies-best-cores-vs-preferred-cores

I do not know at all if the scheduler in Linux kernel is aware of this, but if it is, then these should be the last cores to be disabled by the slider, as it should technically provide either performance or battery life advantages (albeit probably pretty small)

**Comment by NGnius** [comment]
This would be something interesting to investigate! The article seems to indicate that AMD doesn't have support for this in Linux, but that could've changed.

Some caveats to consider/research:
- Does this also affect mobile Zen2 chips? If yes:
  - How does this manifest on power-restricted devices?
  - Do the better cores have better efficiency, or just higher boost limits?
- Can this data be retrieved by an OS other than Windows (or: did MS & AMD make some this proprietary for no good reason)?
- How big is the impact on performance and efficiency?

As it stands, I'm going to mark this as missing information since, through no fault of your own, more research is required.

**Comment by Samuel-B-D** [comment]
[HWiNFO](https://www.hwinfo.com/) is able to list the order of "best-to-worse" cores as shown in the article.
I'll try to do some more research :)

**Comment by NGnius** [comment]
Here's some disappointing research: According to the original article, this feature is exposed through CPPC2, which is part of UEFI (aka the modern BIOS). The Steam Deck uses UEFI, so that's fine.

Unfortunately, the [Linux kernel docs](https://www.kernel.org/doc/html/latest/admin-guide/acpi/cppc_sysfs.html) says that `/sys/devices/system/cpu/cpuX/acpi_cppc/` should exist (where X is a valid cpu number), but it doesn't on the Steam Deck.

[Phoronix suggests](https://www.phoronix.com/news/AMD-New-CPUFreq-CPPC) that CPPC (not 2) support was added a while ago (for Linux kernel 5.3 or 5.4), but is disabled by default. The kernel boot parameter to enable it is not present on my Steam Deck.
```
BOOT_IMAGE=/boot/vmlinuz-linux-neptune console=tty1 rd.luks=0 rd.lvm=0 rd.md=0 rd.dm=0 rd.systemd.gpt_auto=no module_blacklist=tpm amd_iommu=off amdgpu.gttsize=8128 spi_amd.speed_dev=1 audit=0 fbcon=rotate:1 loglevel=3 splash quiet plymouth.ignore-serial-consoles fbcon=vc:4-6 steamos.efi=PARTUUID=<snip>
```
I think [this](https://lkml.org/lkml/2019/7/10/682) is the original patch to add CPPC (still not 2) for AMD Zen 2. I suspect Van Gogh is too special to have gotten support in that.

On the other hand, `/sys/firmware/acpi` and `/sys/firmware/efi` both exist on my Deck, and may have some hidden goodies that I've yet to find.

With some help from some people on the Decky Discord, we've found there's work on [an AMD p-state driver](https://www.phoronix.com/review/amd-pstate-first) (with help from Valve, for the Steam Deck!), but it's [only in 5.17](https://www.phoronix.com/news/AMD-P-State-How-To) and is disabled by default. Steam Deck is 5.13 so that's a no-go.

They also found [this repo](https://github.com/kevinlekiller/amdctl) for setting voltage of lots of AMD CPUs using the `msr` kernel module, which I don't understand at all so that's worth some further research.

**Comment by NGnius** [comment]
Removing milestone and closing this issue since I don't think this is going to work anytime soon. I'm not against revisiting this if it does become possible later, though. The changes for #48 would make a change like this pretty easy to implement once the detection hurdle is overcome.
