### ISSUE TITLE
After the deck UI crashes profile doesn't revert back to default

### ISSUE THREAD

**Issue by Jordonbc** [NGnius/PowerTools#39]
**Expected Behaviour**
When the UI crashes PowerTools reverts back to the default profile

**Actual Behaviour**
When the steam deck UI crashes PowerTools doesn't revert back to default profile e.g. still says I'm using the "Fallout 4" profile

**To Reproduce**
1. *Steam Deck crashes*
2. Open PowerTools menu
3. Look at current Profile

**Screenshots, etc.**
Please include the log (located at `/tmp/powertools.log`) if possible.
Note: the log is deleted when the device is restarted.

**Notes**
- I'm using beta client

**Comment by NGnius** [comment]
I don't plan on working around bugs in other projects. Feel free to make a PR to fix this.

**Comment by Jordonbc** [comment]
What do you mean working around bugs in other projects? What other projects?

**Comment by NGnius** [comment]
It's a bug with gamescope on SteamOS Beta that crashes Steam and stops it from notifying things (like PowerTools) that a game has closed. 

I have no interest in trying to detect when that bug occurs so that PowerTools can handle it properly. In all likelihood it'll be fixed within a few weeks, since the work to fix it seems to have been completed by gamescope devs.

**Comment by Jordonbc** [comment]
oh ok, I didn't realise that it was a bug with steam beta, I got PowerTools yesterday and when accessed the PowerTools menu it would sometimes crash (I saw it was mentioned in an issue already)
