### ISSUE TITLE
"Defaults" button not working

### ISSUE THREAD

**Issue by subworx** [NGnius/PowerTools#44]
**Expected Behaviour**
The "Default" button returns all settings to the default when clicked, no matter which profile is loaded. Especially on the Default profile.

**Actual Behaviour**
Nothing happens.

**To Reproduce**
1. Go to PowerTools settings, check which profile it uses - I assume the Default profile and no game profile now.
2. Change some of the values to your liking: turn stuff on/off, move the sliders a bit.
3. Exit and re-enter PowerTools, just to be sure. Everything still  the way I just set it
4. Click "Defaults".
5. Nothing happens. Reopen PowerTools, the sliders are exactly where I left them instead of in default position and additionally the Limit functions (Frequency Limits, PowerPlay Limits, ...) remains turned on.

**Screenshots, etc.**
`/tmp/powertools.log`: not much to see here.

```
07:12:07 [INFO] Starting back-end (powertools-rs v1.0.5)
07:12:07 [INFO] resume_worker starting...
07:12:07 [INFO] save_worker starting...
07:12:07 [INFO] Server::run; addr=127.0.0.1:44443
07:12:07 [INFO] listening on http://127.0.0.1:44443
```

**Comment by NGnius** [comment]
If you have persistence enabled on the default settings, this is working as intended: loading defaults loads the default settings. If you turn off persistence, this will load the system defaults since that's the fallback default when there's no file.

I'm not entirely happy with that since that behaviour is not obviously correct. If you've got an idea on how it should be, I'd be happy to change this into a enhancement for v1.1.0 (...whenever I get some time to dive into that update).

**Comment by subworx** [comment]
To restore the actual system default to default, I had to remove the config for default. Tried SMT off and 1 core, stuck through persistent on/off with reboots in between, no matter how often I clicked Defaults.

Of course everybody understands things differently.

*My* expectation would be that "Defaults" returns the settings to the stock system defaults, no matter if inside a game or in the Steam UI. 

"Persistence on" for the default profile means the settings survive a reboot, persistence off means after a reboot, everything is back to stock, no matter any configuration files. For games, if persistence is on, re-apply the settings, otherwise drop them after the game closes.

The standard profile outside games is called "Default" as well, so when reverting a game to "Default" with the button, the question would be whether to use the "Default" profile (which maybe needs a rename to "Main" or whatever and may be messed up too) or to the stock system default. This might be part of the confusion.

*But* in the end this is one person's view, while there are thousands of users out there who maybe understand it better - or don't speak up :P and the choice on if and what to change is completely up to you.

So, thank you very much for investing time and effort into this cool plugin :)

**Comment by NGnius** [comment]
> To restore the actual system default to default, I had to remove the config for default.

Ok that sounds like a bug. No idea why that's still happening, because I could've sworn I fixed it in v1.0.5 but that's the thing with bugs -- they tend to be pesky little things.

> My expectation would be that "Defaults" returns the settings to the stock system defaults, no matter if inside a game or in the Steam UI.
>
> "Persistence on" for the default profile means the settings survive a reboot, persistence off means after a reboot, everything is back to stock, no matter any configuration files. For games, if persistence is on, re-apply the settings, otherwise drop them after the game closes.

And I suspect a lot of people would agree with your expectation. Even I do. My reasoning for having it the way it is was to allow for people to accomplish some inheritance between the Main (aka Default; see below) and game profiles, but that subtle behaviour may just be confusing and not all that helpful.

I'm going to have to think a bit about how this can be done well, so I'm not going to fix this until v1.1, where I won't feel so bad about intrusive changes like this. I don't know when I'll get around to that, but hoping for sooner rather than later.

> "Default" profile (which maybe needs a rename to "Main" or whatever...)

This is a good idea, to avoid conflating system defaults with the default setting profile. I'm also considering "Menu", but as with the rest of this I'm going to have to think about this more before I do anything about it. The actual name is quite arbitrary and really just an implementation detail, so I'm not too worried about what it's called as long as it's changed from Default.

Thanks for the insight, I always like to hear other opinions. Having 2 views is still better than 1 (which is what I usually have), so don't sell yourself short.

> So, thank you very much for investing time and effort into this cool plugin :)

No problem! I'm actually a very strange dude who enjoys programming too much, so no thanks is necessary. Regardless, thank you for taking some time to help me out with it.

**Comment by baobab143** [comment]
>For games, if persistence is on, re-apply the settings, otherwise drop them after the game closes.

Adding a vote to this, that's what I would expect the behavior to be.
When persisting settings for a game, a user currently also needs to persist the `Default` profile if they want to restore settings outside of the game. But now it's unclear if these `Default` settings will override the Steam OS ones or not.

Would prefer the way above: as soon as exiting the game with persisted settings, fall back to letting Steam OS manage settings, without having to persist anything else.
If the user wants to override Steam OS settings, then have them explicitly persist `Default` (or a renamed version of it).

**Comment by NGnius** [comment]
> But now it's unclear if these `Default` settings will override the Steam OS ones or not.

This is on purpose, since I can't guarantee either way (see: [race condition](https://en.wikipedia.org/wiki/Race_condition)). I also do not encourage people to have settings enabled in PowerTools that override things in vanilla SteamOS because that's a user error. Use one or the other, not both.

Anyway, the updated behaviour is roughly as described previously but I'll summarize since it's been implemented now. When exiting a game, the `Main` (formerly `Default`) profile is loaded from file. If the file does not exist, the system defaults are loaded instead. The `Defaults` button now always loads the system defaults instead of having the same behaviour as returning from a game.
