### ISSUE TITLE
Persistence setting cannot be disabled, game will continue to use persistence settings instead of global power tool settings.

### ISSUE THREAD

**Issue by dizzyflames** [NGnius/PowerTools#55]
**Expected Behaviour**
Disabling persistence will use global power tools settings.

**Actual Behaviour**
Persistence option turns itself back on when starting the game if it was turned on once previously.
Unable to disable Persistence option for a game to use global power tool settings.

**To Reproduce**
Steps to reproduce the behaviour:
1. Navigate to Power tools
2. Change settings
3. Enable persistence option
4. Disable persistence option
6. Change settings back to default.
7. Relaunch Title
8. Power tools settings reverted to what it was with persistence setting enabled
9. Persistence setting is enabled.

**Comment by NGnius** [comment]
I could've sworn I had fixed that in v1.0.5, but apparently not. Since I'm deep into work on the next feature update now, the fix will be in v1.1. I'll leave this issue open until that update is released.

In the meantime, if anyone is desperate to remove the persistent settings for a game you can manually delete the file `~/.config/powertools/<game id>.json` where `<game id>` is the game ID of the game. You can also search through every file in that folder and look for the json file with the correct `name` field.
