### ISSUE TITLE
Rename "Persistent" to "Use per-game profile"

### ISSUE THREAD

**Issue by MarkoG21** [NGnius/PowerTools#59]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I am doing something good

### Expected Behaviour

Greetings, I have a small suggestion for a change of your app:
I was searching quite a bit, when I was confused as why PowerTools is using the same Profile for every game, even though in the App, it's showing that it uses the game specific profile.
Then I found a Issue where you suggested a user to use the "persistent" setting and now it works.

This lead me to think, why this happened and here are my reasons why I think that "Persistent" is not the best match to describe what the settings does:
- Persistent is another word for permanent, long-lasting, not changing, durable etc. From a language standpoint, I would expect this toggle to apply the settings globally, which is quite contrary to what it actually does. So when choosing a setting to be "Persistent" e.g. activating the button you would expect the changes you have made to be not changing.

- Changing it to "Use per-game profile" would make more sense, since most users probably already understand what this settings does, because this wording is already used in the "Performance" tab which does essentially the same.

### Actual Behaviour

Activating the setting to be persistent makes it not persistent.

### Steps To Reproduce

-

### Version

1.0.5 (Latest stable)

### Version

Steam Deck

**Comment by MarkoG21** [comment]
Oh I apologize for picking the wrong label ^^, didn't quite know in what category to put this suggestion, thanks for fixing it!
Yeah, after reading the description of the toggle, it definetly made sense to me, 
After reading the definition of persistence, associated with computer science, I definetly understand where you are coming from.

I'm also interested about what other opinions there are about this topic, so I hope there will be some other suggestions/points of view too👍

**Comment by BadJanitor** [comment]
I found this issue because I was also confused by the setting.  While I agree that "Persistent" may be the technically correct term from a from a scientific standpoint, but it's not the best term to describe the effect of the setting.  The description helps, but I still interpreted this as a global setting, meaning if it's disabled all PowerTools options are reset to default every reboot.

What about just using both terms and calling it "Persistent Profile", with a description or something like "Restores settings _for this application_ after an app or OS restart"?

**Comment by ekirchman** [comment]
I was actually just pulling the issues page to create a request for a "per game" profile setting. But I stumbled upon this thread saying that it's already a feature? At least I think? The wording of it is confusing, at least to me, even as a native English speaker

**Comment by NGnius** [comment]
Just noticed that my link to the new Peristent toggle description is broken because I refactored that file. The new description reads `Save profile and load it next time`.

"Persistent Profile" is a pretty good option. I'm slightly concerned it's redundant since profile is mentioned in the description *and* it's literally right beside the Profile menu item, but I'll mull it over before the next release drops.

I'm going to keep my new description for at least the next update since it seems to communicate everything that "Restores settings for this plugin after an app or OS restart" does while avoiding being as wordy. I also try to keep the descriptions short enough to fit on one line, though translations aren't required to abide by that (mostly because I know that's a classic problem with French that the Canadian government is all too familiar with).

**Comment by ekirchman** [comment]
I do like "Persistent Profile" better. Using the term "profile" helps keep it in line with Valve's own terminology. 

If you want to make the description line shorter, do you need to keep the "or OS restart" in there? As a developer, I understand why you might put that there; one can't assume that certain configurations will survive a reboot. But as an end user, I expect a "profile" to survive a reboot. 

That's just my own opinion, however. Thanks for taking the time to clarify :)

**Comment by NGnius** [comment]
Y'all have got your wish: [ec97003](https://github.com/NGnius/PowerTools/commit/ec97003e389e5a61ea06291c1d7148b9784cd3f4)
