### ISSUE TITLE
SMT off option will stay active when leaving the game 

### ISSUE THREAD

**Issue by andgtr08** [NGnius/PowerTools#68]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I will fill this out to the best of my ability

### Expected Behaviour

After exiting a game (in my case emulator) with SMT off profile, the plugin should return to default profile (that uses SMT On)

### Actual Behaviour

When playing a game or application with SMT Off, the option will stay disabled (disabling SMT) after exiting. Unless you use other game or application with Persistent profile with SMT On or enabling it again. 

### Steps To Reproduce

1. Set a persistent profile to a game.
2. Disable "SMT" 
3. Exit the game.
4. Open other game with no persistent profile
5. The game now is running with default profile but SMT is disabled.

### Anything else?
A temporary fix is set a persistent profile to the SD home screen with SMT On. That way the plugin will always enable SMT again.

_No response_

### Version

1.0.5 (Latest stable)

### Platform

Steam Deck

### OS

SteamOS 3 (Stable)

**Comment by NGnius** [comment]
Is this not just because your Default (Main menu) profile is not set to persistent? When that's the case, it'll keep whatever settings were last applied.

**Comment by andgtr08** [comment]
> Is this not just because your Default (Main menu) profile is not set to persistent? When that's the case, it'll keep whatever settings were last applied.

That's exactly the case. But the SMT off option should still be active even when exit the game? I thought it would be reversed.

**Comment by NGnius** [comment]
This is working as intended: if you have persistence enabled on the default settings, returning to menu loads the default settings. If you turn off persistence, that action will not do anything since there's no file to override the currently-applied settings.

This is going to change with the next update, so no need to ask for this as an enhancement. For context, see #44 , specifically [this comment](https://github.com/NGnius/PowerTools/issues/44#issuecomment-1368280910).
