### ISSUE TITLE
Error Reference: Shared SteamUI_7834012_9305e8ac929cc2f3      unreachable

### ISSUE THREAD

**Issue by pparmy** [NGnius/PowerTools#71]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I will fill this out to the best of my ability

### Expected Behaviour

I open version 1.1.0 and expect it to open but come across the listed behavior. 2nd latest version works. 

### Actual Behaviour

Something went wrong while displaying this content. Refresh

Error Reference: Shared SteamUI_7834012_9305e8ac929cc2f3
unreachable

### Steps To Reproduce

>click •••
>scroll down to PowerTools
>click on it
>get referenced error

### Version

1.1.0 (Latest stable)

### Platform

Steam Deck

### OS

SteamOS 3 (Stable)

**Comment by NGnius** [comment]
If a full system restart doesn't fix it, Decky and PowerTools logs would be appreciated.

Decky logs can be saved to `/home/deck/decky.log` by running `cd ~ && journalctl -u plugin_loader.service > decky.log`. PowerTools logged are saved at `/tmp/powertools-rs.log`.

**Comment by pparmy** [comment]
What would be the best method of sending them? I get a popup saying the
file is less than 0 bytes when dragging and dropping it here and copy/paste
crashes it.

**Comment by pparmy** [comment]
Also I can't find what you mean by " /tmp/powertools-rs.log."

I tried searching it in Dolphin and found nothing. But I do currently have
issues regarding my btrfs home drive making my steamgames and WIndows
partitions "unknown" if that would have anything to do with why it's
missing..?

**Comment by othyn** [comment]
Also have this issue on a fresh SteamOS installation (had to factory reset due to other issues).

Series of events:

1. Was running v1.0.6.
2. Downloaded the v1.1.0 update.
3. Presented with the 'Something went wrong while displaying this content.' error whenever loading the PowerTools UI.
4. Tried reboots, reinstalls, etc. nothing appeared to fix it, it would always show that error.
5. Reinstalled v1.0.6, worked absolutely fine again.
6. <played some games, left it at that overnight>
7. <rebooted Steam Deck a few times for other misc reasons>
8. Came to this thread, and for the sake of debugging tried to install and use v1.1.0 again so I could pull the logs.
9. Installed the v1.1.0 update, everything is working fine. 🤷

As its now working, and I've rebooted between now and the error happening, I can't provide any useful logs unfortunately.

Also, I have no idea what the reproducable scenario is, which is even more annoying. So far, from the experience I've been through;

1. Install a fresh SteamOS installation.
2. Install Decky Loader.
3. Install PowerTools v1.0.6.
4. Install PowerTools v1.1.0 update.
5. <issue occurs>

But I have no idea if that scenario is actually reliably reproducable.

**Comment by LPDawid** [comment]
I had this too after 1.1.0 update. Standard reboot didn't help. Forced reboot followed by SteamOS auto verification fixed it. I've attached my logs if needed.
[decky.log](https://github.com/NGnius/PowerTools/files/10713684/decky.log)
[powertools-rs.log](https://github.com/NGnius/PowerTools/files/10713685/powertools-rs.log)

**Comment by NGnius** [comment]
I'm still not sure what's causing this and I'm unable to reproduce it. Therefore I have no way of fixing this. Be prepared to wait a while if you can't fix it yourself. I can almost guarantee I am more frustrated than you on this: I wanted to focus on other projects this weekend.

Here's what I've figured out so far:
- The PowerTools back-end (the Rust binary) is failing to start (why?)
- The UI is crashing because vital information is "undefined" (because the back-end isn't running)

I don't have any information to even correlate cases where it is happening. All I can offer is generic troubleshooting advice like make sure everything is up to date, reboot, reinstall, sacrifice some blood to the PC gods, etc.

> Also I can't find what you mean by " /tmp/powertools-rs.log." [sic]

Don't worry about it, `powertools-rs.log` won't exist if the back-end can't start. Though that sounds like the least of your worries if your system can't even upload files. The rest of what you're describing sounds like corruption. I can't help but wonder if your non-standard setup is causing this problem.

**Comment by pparmy** [comment]
Another user mentioned forced reboot, or holding the power button until the
screen shuts off, and after the steam verification popped boot up it
started working! I haven't figured anything out regarding my issue but
contacted the person who made the btrfs home conversion hoping they'd have
an idea.

**Comment by phush0** [comment]
For me update from 1.0.6 to 1.1.0 made decky crash all together and tab with plug disappear completely. Restart fixed it.

**Comment by Pilcrow182** [comment]
Can confirm, same as phush0.

I updated from 1.0.6 to 1.1.0, and then running PowerTools brought me to a screen with this exact error and a 'refresh to continue' button. Upon clicking the button I was dropped back into the Deck's main menu and Decky was no longer loaded.

I tried selecting 'restart steam' from the power menu, which restored Decky, but the bug persisted upon trying to use PowerTools again.

I then tried a _shutdown_ from the power menu, started the Deck again a few minutes later, and PowerTools 1.1.0 was suddenly working fine. I am now using it with no issues.

**Comment by terence4444** [comment]
I had this issue, too. 
From 1.0.6 to 1.1.0, it crashed instantly when I tried clicking PowerTools in Decky.
I waited until 1.1.1 and the issue wasn't solved. Then I uninstalled & re-installed Decky with PowerTools 1.1.1.
It looks like an outdated config or cache caused this issue.

**Comment by NGnius** [comment]
I haven't heard of this happening recently (and I think I fixed it), so I'm going to close this.
